chore(schema): Add property  in AcademicProfileCommentSchema
Laboratoria/schemas pull request #19
Opened 2019-10-10 20:23 UTC by MaiaRojas

2019-10-10 23:47 UTC, RuthMeryCardenas commented
Great job :+1: 
@MaiaRojas , It would be really nice if you could add a description to this PR :smile:

2019-10-11 00:34 UTC, Xpktro requested changes
What Mery said

2019-10-11 00:34 UTC, Xpktro commented on src/AcademicProfileCommentSchema.js
> +        'general',
Good, even though this is considered an `enum value` rather tan a property (which is `type` in this case). Please describe this in your commit message as well.

2019-10-11 22:49 UTC, merycardenas27 approved these changes
![](https://media.giphy.com/media/IfrnnS1OLeeczsa5mo/giphy.gif)

2019-10-11 22:50 UTC, merged