refactor(tag): Add events created and deleted in AcademicProfileTag
Laboratoria/schemas pull request #23
Opened 2019-12-06 19:55 UTC by MaiaRojas

Añade eventos de crear y eliminar Tags.

2019-12-12 17:05 UTC, MaiaRojas commented
> Creo que no debería ser required ya que el MVP plantea el poder agregar una etiqueta al perfil sin incluir la razón.

La mejor solución seria crear el documento con `assignmentReason: 'No comment',` ya que el siguiente sprint se realiza este feature con ese requerimiento

2019-12-12 20:29 UTC, Xpktro requested changes
Left some comments, proceed with caution

2019-12-12 20:29 UTC, Xpktro commented on src/UserActivityFeedEventSchemas/AcademicProfileTagDeletedEventSchema.js
> +    createdBy: {
I've seen a commit updating this name in the changeset. I would suggest to remove it and also consider it to be undone and keep the name as `removedBy` or similar, I think mixing a creation property for a deletion document can lead to confusion

2019-12-12 20:29 UTC, Xpktro commented on src/UserActivityFeedEventSchemas/AcademicProfileTagDeletedEventSchema.js
> +    removalReason: {
if this event uses the `deleted` word, this property must use that word as well

2019-12-12 20:29 UTC, Xpktro commented on src/UserActivityFeedEventSchemas/AcademicProfileTagCreatedEventSchema.js
> +    assignmentReason: {
Is this tag created? (as in `AcademicProfileTagCreated...`) or assigned? 😅

2019-12-12 20:29 UTC, Xpktro commented on src/UserActivityFeedEventSchemas/TagCreatedEventSchema.js
> +  const ReviewTagCreatedEventSchema = new conn.Schema({
are review tags any different than the academic profile ones? or do we actually care where such tags are being created for event tracking? I'd advocate for using only one schema and provide a discriminator field, or nothing at all (if the answer for those two questions is NO)

2019-12-12 20:29 UTC, raulingg commented on src/UserActivityFeedEventSchemas/AcademicProfileTagCreatedEventSchema.js
> +  AcademicProfileTagCreatedEventSchema.pre('save', function (next) {
I believe We are creating mongoose hooks in `models` repo rather than `schemas` repo.

can we move it to  `models` repo.

2019-12-12 20:34 UTC, raulingg submitted a review, later dismissed
@MaiaRojas can we meet?

2019-12-13 20:04 UTC, Xpktro approved these changes

2019-12-13 20:05 UTC, Xpktro approved these changes

2019-12-13 20:07 UTC, merged